Checkout:
	git submodule update --init --recursive

Build:
	cd rocket-chip/riscv-tools; bash ./build.sh
	source /opt/Xilinx/Vivado/2018.1/settings64.sh; source set_env.sh; make -C fpga/board/nexys4_ddr bitstream

Test:
	echo Test

Deploy:
	echo Deploy
